_C='The connector file was not found in the app assets.\nPlease download it separately from the project repository.'
_B='README.txt'
_A=True
import io,zipfile,os
from pathlib import Path
from typing import BinaryIO
ASSETS_DIR=Path(__file__).parent.parent/'assets'
CONNECTOR_FILENAME='SnowflakeSemanticViews.mez'
def get_readme_content():return'# Snowflake Semantic Views - Power BI Semantic Model\n\n## Quick Start\n\n1. **Install the Custom Connector**\n   - Copy `connector/SnowflakeSemanticViews.mez` to:\n     - Windows: `Documents\\Power BI Desktop\\Custom Connectors\\`\n     - Mac: `Documents/Power BI Desktop/Custom Connectors/`\n   - Create the "Custom Connectors" folder if it doesn\'t exist\n\n2. **Enable Custom Connectors in Power BI Desktop**\n   - Open Power BI Desktop\n   - Go to File > Options and settings > Options\n   - Select "Security" from the left menu\n   - Under "Data Extensions", select "(Not Recommended) Allow any extension..."\n   - Click OK and restart Power BI Desktop\n\n3. **Open the Model**\n   - Double-click the `.pbip` file in this package\n   - Power BI Desktop will open with the semantic model loaded\n   - You may be prompted to enter your Snowflake credentials\n\n4. **Start Building Reports**\n   - The semantic views are now available in the Fields pane\n   - Drag and drop dimensions and metrics to create visualizations\n   - DirectQuery mode ensures real-time data from Snowflake\n\n## Troubleshooting\n\n### "Unknown extension" error\nMake sure you:\n1. Copied the `.mez` file to the correct Custom Connectors folder\n2. Enabled "Allow any extension" in Power BI security settings\n3. Restarted Power BI Desktop after making changes\n\n### Authentication issues\nThe connector supports:\n- Username/Password authentication\n- SSO (Single Sign-On) - if configured in Snowflake\n\n### Data not loading\n- Verify your Snowflake credentials\n- Check that you have access to the database/schema/views\n- Ensure your Snowflake warehouse is running\n\n## Files in This Package\n\n- `*.pbip` - Power BI Project file (open this)\n- `*.SemanticModel/` - Model definition (TMDL format)\n- `*.Report/` - Empty report template\n- `connector/` - Custom connector file\n- `README.txt` - This file\n\n## Support\n\nFor issues with:\n- The connector: Check the project repository\n- Power BI: Visit https://support.microsoft.com/power-bi\n- Snowflake: Visit https://community.snowflake.com\n\nGenerated by Snowflake Semantic Views Power BI Generator\n'
def read_connector_file():
	A=ASSETS_DIR/CONNECTOR_FILENAME
	if A.exists():return A.read_bytes()
def create_zip_with_connector(tmdl_files,include_connector=_A,include_readme=_A):
	B=io.BytesIO()
	with zipfile.ZipFile(B,'w',zipfile.ZIP_DEFLATED)as A:
		for(D,E)in tmdl_files.items():A.writestr(D,E)
		if include_readme:A.writestr(_B,get_readme_content())
		if include_connector:
			C=read_connector_file()
			if C:A.writestr(f"connector/{CONNECTOR_FILENAME}",C)
			else:A.writestr('connector/CONNECTOR_NOT_FOUND.txt',_C)
	B.seek(0);return B.getvalue()
def create_connector_only_zip():
	A=io.BytesIO()
	with zipfile.ZipFile(A,'w',zipfile.ZIP_DEFLATED)as B:
		C=read_connector_file()
		if C:B.writestr(CONNECTOR_FILENAME,C)
		D='# Snowflake Semantic Views Connector - Installation\n\n## Installation Steps\n\n1. **Locate or Create the Custom Connectors Folder**\n   - Windows: `Documents\\Power BI Desktop\\Custom Connectors\\`\n   - Mac: `Documents/Power BI Desktop/Custom Connectors/`\n\n2. **Copy the Connector**\n   - Extract `SnowflakeSemanticViews.mez` from this ZIP\n   - Copy it to the Custom Connectors folder\n\n3. **Enable Custom Connectors in Power BI Desktop**\n   - Open Power BI Desktop\n   - Go to File > Options and settings > Options\n   - Select "Security" from the left menu\n   - Under "Data Extensions", select "(Not Recommended) Allow any extension..."\n   - Click OK\n\n4. **Restart Power BI Desktop**\n   - Close and reopen Power BI Desktop\n   - The connector will now appear in Get Data\n\n## Using the Connector\n\n1. In Power BI Desktop, click "Get Data"\n2. Search for "Snowflake Semantic Views"\n3. Enter your Snowflake server (e.g., account.snowflakecomputing.com)\n4. Enter your warehouse name\n5. Navigate to the database > schema > semantic view\n6. Select DirectQuery mode for real-time data\n\n## Requirements\n\n- Power BI Desktop (latest version recommended)\n- Snowflake account with access to semantic views\n- Valid Snowflake credentials\n\n## Troubleshooting\n\nIf the connector doesn\'t appear:\n1. Verify the .mez file is in the correct folder\n2. Check that custom connectors are enabled in Options\n3. Restart Power BI Desktop completely\n';B.writestr('INSTALL.txt',D)
	A.seek(0);return A.getvalue()
def get_connector_bytes():return read_connector_file()
def get_pbit_readme_content():return'# Snowflake Semantic Views - Power BI Template\n\n## Quick Start\n\n1. **Install the Custom Connector (Required)**\n   - Copy `SnowflakeSemanticViews.mez` to:\n     - Windows: `Documents\\Power BI Desktop\\Custom Connectors\\`\n     - Mac: `Documents/Power BI Desktop/Custom Connectors/`\n   - Create the "Custom Connectors" folder if it doesn\'t exist\n\n2. **Enable Custom Connectors in Power BI Desktop**\n   - Open Power BI Desktop\n   - Go to File > Options and settings > Options\n   - Select "Security" from the left menu\n   - Under "Data Extensions", select "(Not Recommended) Allow any extension..."\n   - Click OK and restart Power BI Desktop\n\n3. **Open the Template**\n   - Double-click the `.pbit` file\n   - Power BI Desktop will open and prompt for credentials\n   - Enter your Snowflake username and password\n\n4. **Save as PBIX**\n   - After connecting, save the file as `.pbix` to store your credentials\n   - Your data model is ready for building reports!\n\n## Troubleshooting\n\n### "Unknown extension" error\nMake sure you:\n1. Copied the `.mez` file to the correct Custom Connectors folder\n2. Enabled "Allow any extension" in Power BI security settings\n3. Restarted Power BI Desktop after making changes\n\n### "Could not find Mashup function"\nThis means the custom connector is not installed properly.\n1. Close Power BI Desktop completely\n2. Copy the .mez file to Custom Connectors folder\n3. Enable custom connectors in Power BI options\n4. Restart Power BI Desktop\n\n## Files in This Package\n\n- `*.pbit` - Power BI Template file (open this)\n- `SnowflakeSemanticViews.mez` - Custom connector (install first)\n- `README.txt` - This file\n\n## Support\n\nFor issues with:\n- The connector: Check the project repository\n- Power BI: Visit https://support.microsoft.com/power-bi\n- Snowflake: Visit https://community.snowflake.com\n\nGenerated by Snowflake Semantic Views Power BI Generator\n'
def create_pbit_with_connector(pbit_bytes,project_name,include_connector=_A,include_readme=_A):
	B=io.BytesIO()
	with zipfile.ZipFile(B,'w',zipfile.ZIP_DEFLATED)as A:
		A.writestr(f"{project_name}.pbit",pbit_bytes)
		if include_readme:A.writestr(_B,get_pbit_readme_content())
		if include_connector:
			C=read_connector_file()
			if C:A.writestr(CONNECTOR_FILENAME,C)
			else:A.writestr('CONNECTOR_NOT_FOUND.txt',_C)
	B.seek(0);return B.getvalue()