"""
ZIP packager for TMDL projects.
Creates downloadable ZIP files containing TMDL files and the connector.
"""

import io
import zipfile
import os
from pathlib import Path
from typing import BinaryIO


# Path to assets folder (relative to this file)
ASSETS_DIR = Path(__file__).parent.parent / "assets"
CONNECTOR_FILENAME = "SnowflakeSemanticViews.mez"


def get_readme_content() -> str:
    """
    Generate README content with installation instructions.

    Returns:
        README text content
    """
    return """# Snowflake Semantic Views - Power BI Semantic Model

## Quick Start

1. **Install the Custom Connector**
   - Copy `connector/SnowflakeSemanticViews.mez` to:
     - Windows: `Documents\\Power BI Desktop\\Custom Connectors\\`
     - Mac: `Documents/Power BI Desktop/Custom Connectors/`
   - Create the "Custom Connectors" folder if it doesn't exist

2. **Enable Custom Connectors in Power BI Desktop**
   - Open Power BI Desktop
   - Go to File > Options and settings > Options
   - Select "Security" from the left menu
   - Under "Data Extensions", select "(Not Recommended) Allow any extension..."
   - Click OK and restart Power BI Desktop

3. **Open the Model**
   - Double-click the `.pbip` file in this package
   - Power BI Desktop will open with the semantic model loaded
   - You may be prompted to enter your Snowflake credentials

4. **Start Building Reports**
   - The semantic views are now available in the Fields pane
   - Drag and drop dimensions and metrics to create visualizations
   - DirectQuery mode ensures real-time data from Snowflake

## Troubleshooting

### "Unknown extension" error
Make sure you:
1. Copied the `.mez` file to the correct Custom Connectors folder
2. Enabled "Allow any extension" in Power BI security settings
3. Restarted Power BI Desktop after making changes

### Authentication issues
The connector supports:
- Username/Password authentication
- SSO (Single Sign-On) - if configured in Snowflake

### Data not loading
- Verify your Snowflake credentials
- Check that you have access to the database/schema/views
- Ensure your Snowflake warehouse is running

## Files in This Package

- `*.pbip` - Power BI Project file (open this)
- `*.SemanticModel/` - Model definition (TMDL format)
- `*.Report/` - Empty report template
- `connector/` - Custom connector file
- `README.txt` - This file

## Support

For issues with:
- The connector: Check the project repository
- Power BI: Visit https://support.microsoft.com/power-bi
- Snowflake: Visit https://community.snowflake.com

Generated by Snowflake Semantic Views Power BI Generator
"""


def read_connector_file() -> bytes | None:
    """
    Read the connector .mez file from assets.

    Returns:
        Connector file bytes, or None if not found
    """
    connector_path = ASSETS_DIR / CONNECTOR_FILENAME
    if connector_path.exists():
        return connector_path.read_bytes()
    return None


def create_zip_with_connector(
    tmdl_files: dict[str, str],
    include_connector: bool = True,
    include_readme: bool = True
) -> bytes:
    """
    Create a ZIP file containing TMDL project files and optionally the connector.

    Args:
        tmdl_files: Dictionary mapping file paths to file contents
        include_connector: Whether to include the .mez connector
        include_readme: Whether to include README.txt

    Returns:
        ZIP file as bytes
    """
    zip_buffer = io.BytesIO()

    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        # Add TMDL files
        for file_path, content in tmdl_files.items():
            zf.writestr(file_path, content)

        # Add README
        if include_readme:
            zf.writestr("README.txt", get_readme_content())

        # Add connector
        if include_connector:
            connector_bytes = read_connector_file()
            if connector_bytes:
                zf.writestr(f"connector/{CONNECTOR_FILENAME}", connector_bytes)
            else:
                # If connector not found, add a placeholder note
                zf.writestr(
                    "connector/CONNECTOR_NOT_FOUND.txt",
                    "The connector file was not found in the app assets.\n"
                    "Please download it separately from the project repository."
                )

    zip_buffer.seek(0)
    return zip_buffer.getvalue()


def create_connector_only_zip() -> bytes:
    """
    Create a ZIP file containing only the connector and installation instructions.

    Returns:
        ZIP file as bytes
    """
    zip_buffer = io.BytesIO()

    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        # Add connector
        connector_bytes = read_connector_file()
        if connector_bytes:
            zf.writestr(CONNECTOR_FILENAME, connector_bytes)

        # Add installation instructions
        install_instructions = """# Snowflake Semantic Views Connector - Installation

## Installation Steps

1. **Locate or Create the Custom Connectors Folder**
   - Windows: `Documents\\Power BI Desktop\\Custom Connectors\\`
   - Mac: `Documents/Power BI Desktop/Custom Connectors/`

2. **Copy the Connector**
   - Extract `SnowflakeSemanticViews.mez` from this ZIP
   - Copy it to the Custom Connectors folder

3. **Enable Custom Connectors in Power BI Desktop**
   - Open Power BI Desktop
   - Go to File > Options and settings > Options
   - Select "Security" from the left menu
   - Under "Data Extensions", select "(Not Recommended) Allow any extension..."
   - Click OK

4. **Restart Power BI Desktop**
   - Close and reopen Power BI Desktop
   - The connector will now appear in Get Data

## Using the Connector

1. In Power BI Desktop, click "Get Data"
2. Search for "Snowflake Semantic Views"
3. Enter your Snowflake server (e.g., account.snowflakecomputing.com)
4. Enter your warehouse name
5. Navigate to the database > schema > semantic view
6. Select DirectQuery mode for real-time data

## Requirements

- Power BI Desktop (latest version recommended)
- Snowflake account with access to semantic views
- Valid Snowflake credentials

## Troubleshooting

If the connector doesn't appear:
1. Verify the .mez file is in the correct folder
2. Check that custom connectors are enabled in Options
3. Restart Power BI Desktop completely
"""
        zf.writestr("INSTALL.txt", install_instructions)

    zip_buffer.seek(0)
    return zip_buffer.getvalue()


def get_connector_bytes() -> bytes | None:
    """
    Get the connector file bytes directly (for download button).

    Returns:
        Connector .mez file bytes, or None if not found
    """
    return read_connector_file()


def get_pbit_readme_content() -> str:
    """
    Generate README content for PBIT package.

    Returns:
        README text content
    """
    return """# Snowflake Semantic Views - Power BI Template

## Quick Start

1. **Install the Custom Connector (Required)**
   - Copy `SnowflakeSemanticViews.mez` to:
     - Windows: `Documents\\Power BI Desktop\\Custom Connectors\\`
     - Mac: `Documents/Power BI Desktop/Custom Connectors/`
   - Create the "Custom Connectors" folder if it doesn't exist

2. **Enable Custom Connectors in Power BI Desktop**
   - Open Power BI Desktop
   - Go to File > Options and settings > Options
   - Select "Security" from the left menu
   - Under "Data Extensions", select "(Not Recommended) Allow any extension..."
   - Click OK and restart Power BI Desktop

3. **Open the Template**
   - Double-click the `.pbit` file
   - Power BI Desktop will open and prompt for credentials
   - Enter your Snowflake username and password

4. **Save as PBIX**
   - After connecting, save the file as `.pbix` to store your credentials
   - Your data model is ready for building reports!

## Troubleshooting

### "Unknown extension" error
Make sure you:
1. Copied the `.mez` file to the correct Custom Connectors folder
2. Enabled "Allow any extension" in Power BI security settings
3. Restarted Power BI Desktop after making changes

### "Could not find Mashup function"
This means the custom connector is not installed properly.
1. Close Power BI Desktop completely
2. Copy the .mez file to Custom Connectors folder
3. Enable custom connectors in Power BI options
4. Restart Power BI Desktop

## Files in This Package

- `*.pbit` - Power BI Template file (open this)
- `SnowflakeSemanticViews.mez` - Custom connector (install first)
- `README.txt` - This file

## Support

For issues with:
- The connector: Check the project repository
- Power BI: Visit https://support.microsoft.com/power-bi
- Snowflake: Visit https://community.snowflake.com

Generated by Snowflake Semantic Views Power BI Generator
"""


def create_pbit_with_connector(
    pbit_bytes: bytes,
    project_name: str,
    include_connector: bool = True,
    include_readme: bool = True
) -> bytes:
    """
    Create a ZIP file containing the PBIT file and optionally the connector.

    Args:
        pbit_bytes: The PBIT file as bytes
        project_name: Name for the PBIT file
        include_connector: Whether to include the .mez connector
        include_readme: Whether to include README.txt

    Returns:
        ZIP file as bytes
    """
    zip_buffer = io.BytesIO()

    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        # Add PBIT file
        zf.writestr(f"{project_name}.pbit", pbit_bytes)

        # Add README
        if include_readme:
            zf.writestr("README.txt", get_pbit_readme_content())

        # Add connector
        if include_connector:
            connector_bytes = read_connector_file()
            if connector_bytes:
                zf.writestr(CONNECTOR_FILENAME, connector_bytes)
            else:
                zf.writestr(
                    "CONNECTOR_NOT_FOUND.txt",
                    "The connector file was not found in the app assets.\n"
                    "Please download it separately from the project repository."
                )

    zip_buffer.seek(0)
    return zip_buffer.getvalue()
